export const ErrorCode = {
  PARSE_ERROR: 'PARSE_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNKNOWN_OPERATION: 'UNKNOWN_OPERATION',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  BACKPRESSURE: 'BACKPRESSURE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BUCKET_NOT_DEFINED: 'BUCKET_NOT_DEFINED',
  QUERY_NOT_DEFINED: 'QUERY_NOT_DEFINED',
  RULES_NOT_AVAILABLE: 'RULES_NOT_AVAILABLE',
  SESSION_REVOKED: 'SESSION_REVOKED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
